[package]
name = "cosmic-workspaces"
version = "0.1.0"
edition = "2021"

[dependencies]
calloop = { version = "0.12.2", features = ["executor"] }
cctk = { package = "cosmic-client-toolkit", git = "https://github.com/pop-os/cosmic-protocols", branch = "update-deps-dmabuf" }
env_logger = "0.10.0"
futures-channel = "0.3.25"
libcosmic = { git = "https://github.com/pop-os/libcosmic", default-features = false, features = ["tokio", "wayland"] }
tokio = "1.23.0"
wayland-protocols = "0.31.0"
zbus = { version = "3.7.0", default-features = false, features = ["tokio"] }

[profile.dev]
# Not usable at opt-level 0, at least with software renderer
opt-level = 1
